language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - cd photo-gallery && npm run build
deploy:
  provider: pages
  keep_history: true
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  target_branch: gh-pages
  on:
    branch: master